### ISSUE TITLE
(version 1.2.3) Issue on sending an otp using Verify().call method with verification code of digits greater than 5

### ISSUE THREAD

**Issue by Shyamala7** [TeleSign/python_telesign#14]
When we trigger sms with 7 digit it works but for call it works for a maximum of 5 digits

**Comment by ramsay** [comment]
Hi,
Thanks for using the SDK. The limits of verification code length are something TeleSign Support can help you configure and it is not controlled within the SDK. Please contact support@telesign.com so we can adjust the verification code length limit for your account.
