### ISSUE TITLE
Message not delivering

### ISSUE THREAD

**Issue by thameemkj** [TeleSign/python_telesign#15]
Even though getting status 290, message is not delivering to the given number.
I used the example given in README.rst and the number i gave was verified number(number i used to register).But still cant recieve message to my phone.

**Comment by adohertyTS** [comment]
Hi @thameemkj, I realize it is likely too late to help you with this issue, but here are a few steps you can take to troubleshoot SMS delivery:
1) Check for any country-specific outages on the [Telesign System Status](https://status.telesign.com/) page.
2) Make sure that the latest software updates are present on the phone, and that there are no applications interfering or filtering incoming SMS messages.
3) Restart the device to force it to reconnect to the local base station.
4) Re-test message delivery to check if the problem still persists.
5) Re-test using the same SIM card with a different handset and vice versa.
