### ISSUE TITLE
Only sdist available in pypi

### ISSUE THREAD

**Issue by ghandic** [TeleSign/python_telesign#17]
Could you release a `.whl` to pypi ? At the moment you only release a `.tar.gz` source distribution - it would be ideal if a pipeline was set up to create `.whl`'s for linux, mac (M1 and intel), windows

**Comment by adohertyTS** [comment]
Hi @ghandic ! Thank you for the suggestion. Our product team will consider this feature request. If there is more detail you wish to provide on how adding .whl distribution would help you, please feel free to share.

**Comment by adohertyTS** [comment]
Hi @ghandic , we have just added a wheel to the most recent distribution on Pypi, and would welcome your feedback: https://pypi.org/project/telesign/#files
