### ISSUE TITLE
Problem with installing telesign 1.1.0 through pip

### ISSUE THREAD

**Issue by nkovshov** [TeleSign/python_telesign#8]
Hi Telesign,
I tried to install telesign, but met with problem:
telesign==1.1.0 doesn't installs correctly via pip:
```
>>> import telesign.api
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/virtualenv/experience/local/lib/python2.7/site-packages/telesign/api.py", line 14, in <module>
    from telesign import __version__
ImportError: cannot import name __version__
```
Pip doesn't copy `__init__.py` of telesign package, which contains `__version__` definition. 

Downloading through pip -d and manual installation working correctly. 
I repeated it on two different machines. When I installing telesign==1.0.4, `__init__.py` copying correctly.

**Comment by jayfoo** [comment]
Thanks for finding this.   I'll check this morning to see whats up and we'll probably have a new version in pip today.

**Comment by jarradsl** [comment]
This seems to be a problem with defining the telesign package as a namespace package. Since we don't actually need that functionality it's now defined as a regular old package.
